{{- if and .Values.model.hfToken (not .Values.model.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sglang-ananke.fullname" . }}-hf-token
  labels:
    {{- include "sglang-ananke.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.model.hfToken | b64enc | quote }}
{{- end }}
